apiVersion: apps/v1
kind : Deployment
metadata:
  name: flask-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-app
  template:
      metadata:
        labels:
          name: web-app
      spec:
        containers:
          - name : flask-app
            image: youssefhb/flask_kube:latest
            ports:
              - containerPort : 5000 # Exposes port 5000 of the container
            env:
              - name: PORT
                value: "5000"
---
apiVersion : v1
kind : Service
metadata:
  name: flask-web-app
  namespace: default
spec:
  type: NodePort
  selector:
    name: web-app
  ports:
    - name: web-app-port
      protocol: TCP
      port: 5000



